version: 0.2
phases:
  build:
    commands:
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  post_build:
    commands:
      - echo $IMAGE_TAG > code_hash.txt
artifacts:
  files:
    - '**/*'
